#!/bin/sh

# be sure to run this script with init=/linuxrc

TIMEOUT=3

echo "initrd init script, PID:$$"

mkdir -p /dev
mkdir -p /proc
mkdir -p /sys
mkdir -p /rootfs

mount -t devtmpfs   none            /dev
mount -t proc       proc            /proc
mount -t sysfs      none            /sys

for (( i=$TIMEOUT; i>0; i--)); do
    printf "\rHit any key in $i second to enter shell."
    read -s -n 1 -t 1 key
    if [ $? -eq 0 ]
    then
        break
    fi
done

echo "linuxrc: mount mmc partition 3 as rootfs"
mount -t ext4       /dev/mmcblk0p3  /rootfs

mkdir -p /rootfs/initrd

cd /rootfs

echo "linuxrc: pivot root"
pivot_root . initrd

echo "linuxrc: chroot"

# exec chroot . /bin/bash <dev/console >dev/console 2>&1
exec chroot . /sbin/init <dev/console >dev/console 2>&1
# exec /bin/busybox sh

