#!/bin/busybox sh

FILE=

SPI_NOR="/usb/spi_nor.bin"
FIRMWARE="/usb/firmware.bin"
EMMC_IMG="/usb/emmc.img"

mount -t devtmpfs   none            /dev
mount -t proc       none            /proc
mount -t sysfs      none            /sys
mount -t devpts     none            /dev/pts

echo "----------------------------------------"
echo "SPI_Burn"
echo "----------------------------------------"
echo "This USB drive automatically flash SPI Nor Flash."
echo "init script, PID:$$"
echo "----------------------------------------"
echo "sleep 5 seconds waiting for sda1"

sleep 5

echo "check for sda1"
if [ ! -e "/dev/sda1" ]; then

    # dev file error
    echo "/dev/sda1 does NOT exist"
    # LED off
    echo "PWR_LED 0" > /proc/BOARD_io
    # fallback to shell

else 
    echo "/dev/sda1 found"

    cd /
    mkdir -p usb
    mount -t auto /dev/sda1 usb
    RESULT=$?

    if [ $RESULT -ne 0 ]; then
        # mount failed
        echo "mount usb drive failed."
        # LED orange ON
        echo "PWR_LED 6" > /proc/BOARD_io
        # fallback to shell
    else        
        # mount success
        echo "/dev/sda1 mounted to /usb"
        
        # search for flashable file
        if [ ! -f $SPI_NOR ] && [ ! -f $FIRMWARE ] && [ ! -f $EMMC_IMG ]; then
            # Neither file exist, LED orange slow flash        
            echo "PWR_LED 5" > /proc/BOARD_io
            echo "no flashable file found"
        else
            # at least one file exists
            # LED fast blink white
            echo "PWR_LED 3" > /proc/BOARD_io

            if [ -f $SPI_NOR ]; then
                echo "$SPI_NOR found"
                dd if=$SPI_NOR | pv | dd of=/dev/mtdblock0
            elif [ -f $FIRMWARE ]; then
                echo "$FIRMWARE found"
                # not implemented yet
            elif [ -f $EMMC_IMG ]; then
                echo "$EMMC_IMG found"
                dd if=$EMMC_IMG | pv | dd of=/dev/mmcblk0
            fi

            if [ $? -eq 0 ]; then
                # success, 
                echo "PWR_LED 1" > /proc/BOARD_io
                echo "spi or emmc flash success..."
                echo "Please unplug USB drive and power cycle system"
            else
                # fail
                echo "PWR_LED 4" > /proc/BOARD_io
                echo "spi or emmc flash failed..."
                echo "Please try again or try another board"
            fi
            # fallback to shell
        fi
    fi
fi

exec /bin/busybox sh





