#!/bin/sh

# be sure to run this script with init=/linuxrc
echo "linuxrc script, PID:$$"

mkdir -p /dev
mkdir -p /proc
mkdir -p /sys
mkdir -p /rootfs

mount -t devtmpfs   none            /dev
mount -t proc       proc            /proc
mount -t sysfs      none            /sys

INTERRUPT=
 
for (( i=5; i>0; i--)); do
    printf "\rPress ANY KEY within $i seconds to disable automatic boot."
    read -s -n 1 -t 1 key
    if [ $? -eq 0 ]
    then
        INTERRUPT="yes"
        break
    fi
done
 
if [ "$INTERRUPT" = "yes" ]
then
    # 
    # user interrupted, enter shell
    #
    exec /bin/busybox sh
else
    #
    # no user interrupt
    #
    
    # mount rootfs
    mount -t ext4 /dev/mmcblk0p3 /rootfs
    
    # make initrd mount point
    mkdir -p /rootfs/initrd
    cd /rootfs

    # do pivot_root
    echo "linuxrc: pivot root"
    pivot_root . initrd

    # do chroot
    echo "linuxrc: chroot"
    # exec chroot . /bin/bash <dev/console >dev/console 2>&1
    exec chroot . /sbin/init <dev/console >dev/console 2>&1
fi



