#!/bin/bash

cd workspace

rm -rf lib_modules.tar.gz

# make toolchain
make toolchain

# tar toolchain target installation (mostly lib file)
tar -czf target/ramdisk/toolchain_install.tar.gz -C project_build_i686/IntelCE/root/ .

make

tar -czf lib_modules.tar.gz -C project_build_i686/IntelCE/root/lib/modules .
