#!/bin/bash

set -e

USB_ROOTDIR=/media/usb
BOOT_DIR=/media/usb/boot
TMP_DIR=/media/usb/tmp

mount -t devpts none /dev/pts                                                                                                                             
mount -t proc none /proc
mount -t sysfs none /sys
mount -t ext4 /dev/sda1 /media/usb

apt-get install build-essential
apt-get install kernel-package

mkdir ${TMP_DIR}

tar xvzf ${BOOT_DIR}/linux-2.6.39.tar.gz -C ${TMP_DIR}
cp ${BOOT_DIR}/kernel_config ${TMP_DIR}/.config

cd ${TMP_DIR}
make-kpkg --rootcmd fakeroot --initrd kernel_image kernel_headers
cd -



