#! /bin/sh

. /usr/share/debconf/confmodule

if db_get auto-install/enable && [ "$RET" = true ]; then
	# disable locale & kbd selection for now
	echo 1 >/var/run/auto-install.active
	# find at least one preseed
	if [ ! -e /preseed.cfg ] &&
	   { db_get preseed/url  || [ -z "$RET" ]; } &&
	   { db_get preseed/file || [ -z "$RET" ]; }; then
		# register that no preseed was specified
		touch /var/run/preseed_unspecified_at_boot
	fi
fi
